export const createBitbucketBranch = async (workspace, repo, branchName, fromBranch = 'main') => {
  if (!workspace || !repo) {
    return { success: false, error: 'Bitbucket workspace and repository not configured. Please set them in Settings.' };
  }

  const body = {
    name: branchName,
    target: { hash: fromBranch }
  };

  try {
    const res = await fetch(`/api/bitbucket/repositories/${workspace}/${repo}/refs/branches`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    const data = await res.json();
    if (res.ok) {
      return {
        success: true,
        name: data.name,
        url: `https://bitbucket.org/${workspace}/${repo}/branch/${data.name}`
      };
    } else {
      return { success: false, error: data.error?.message || JSON.stringify(data) };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const getBitbucketBranchName = (jiraKey, storyTitle) => {
  const slug = storyTitle
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 40);
  return `feature/${jiraKey}-${slug}`;
};

export const getBitbucketWorkspaces = async () => {
  try {
    const res = await fetch('/api/bitbucket/workspaces');
    if (res.ok) {
      const data = await res.json();
      return data.values || [];
    }
    return [];
  } catch {
    return [];
  }
};

export const createBitbucketPR = async (workspace, repo, branchName, storyTitle, checklist, jiraKey, defaultBranch = 'main') => {
  if (!workspace || !repo) {
    return { success: false, error: 'Bitbucket workspace and repository not configured.' };
  }

  const description = [
    checklist ? `## PR Review Checklist\n\n${checklist}` : '',
    `---\n*Generated by SDLC Autopilot${jiraKey ? ` · Jira: [${jiraKey}]` : ''}*`
  ].filter(Boolean).join('\n\n');

  const body = {
    title: jiraKey ? `[${jiraKey}] ${storyTitle}` : storyTitle,
    description,
    source: { branch: { name: branchName } },
    destination: { branch: { name: defaultBranch } },
    close_source_branch: false
  };

  try {
    const res = await fetch(`/api/bitbucket/repositories/${workspace}/${repo}/pullrequests`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    const data = await res.json();
    if (res.ok) {
      return {
        success: true,
        id: data.id,
        url: data.links?.html?.href || `https://bitbucket.org/${workspace}/${repo}/pull-requests/${data.id}`
      };
    } else {
      return { success: false, error: data.error?.message || JSON.stringify(data) };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
};

const EXT_LANG_MAP = {
  js: 'javascript', jsx: 'jsx', ts: 'typescript', tsx: 'tsx',
  py: 'python', java: 'java', rb: 'ruby', go: 'go', rs: 'rust',
  cs: 'csharp', php: 'php', swift: 'swift', kt: 'kotlin',
  json: 'json', yaml: 'yaml', yml: 'yaml', md: 'markdown',
  html: 'html', css: 'css', scss: 'scss', sql: 'sql', sh: 'bash'
};

const getLanguage = (path) => {
  const ext = path.split('.').pop()?.toLowerCase();
  return EXT_LANG_MAP[ext] || ext || 'text';
};

const fetchDirListing = async (workspace, repo, branch, subPath = '') => {
  try {
    const path = subPath
      ? `/api/bitbucket/repositories/${workspace}/${repo}/src/${branch}/${subPath}?pagelen=100`
      : `/api/bitbucket/repositories/${workspace}/${repo}/src/${branch}/?pagelen=100`;
    const res = await fetch(path);
    if (!res.ok) return [];
    const data = await res.json();
    return data.values || [];
  } catch {
    return [];
  }
};

export const fetchRepoTree = async (workspace, repo, branch = 'main') => {
  if (!workspace || !repo) return [];
  const root = await fetchDirListing(workspace, repo, branch);
  const all = [...root];

  // Drill one level into common source directories
  const sourceDirs = ['src', 'app', 'lib', 'api', 'services', 'components', 'routes', 'controllers'];
  const subDirs = root.filter(e => e.type === 'commit_directory' && sourceDirs.includes(e.path));
  for (const dir of subDirs.slice(0, 4)) {
    const children = await fetchDirListing(workspace, repo, branch, dir.path);
    all.push(...children);
  }
  return all;
};

export const fetchFileContent = async (workspace, repo, filePath, branch = 'main') => {
  try {
    const res = await fetch(`/api/bitbucket/repositories/${workspace}/${repo}/src/${branch}/${filePath}`);
    if (!res.ok) return null;
    const text = await res.text();
    return text.slice(0, 3000); // cap to control AI token usage
  } catch {
    return null;
  }
};

export const fetchRepoContext = async (workspace, repo, branch = 'main', storyLabels = [], storyTitle = '') => {
  if (!workspace || !repo) return { structure: '', files: [] };

  const entries = await fetchRepoTree(workspace, repo, branch);
  const files = entries.filter(e => e.type === 'commit_file');
  const dirs = [...new Set(entries.filter(e => e.type === 'commit_directory').map(e => e.path))];

  const structure = [
    `Directories: ${dirs.join(', ') || 'none'}`,
    `Files (${files.length}): ${files.map(f => f.path).join(', ').slice(0, 600)}`
  ].join('\n');

  // Always include entry/config files for tech stack detection
  const configNames = ['package.json', 'requirements.txt', 'go.mod', 'pom.xml',
    'index.js', 'app.js', 'main.py', 'app.py', 'main.ts', 'index.ts', 'server.js'];
  const configFiles = files.filter(f => configNames.some(n => f.path.endsWith(n)));

  // Keyword-match remaining files against story labels + title words
  const keywords = [
    ...storyLabels,
    ...storyTitle.toLowerCase().split(/\s+/).filter(w => w.length > 3)
  ].map(k => k.toLowerCase());

  const matchedFiles = keywords.length > 0
    ? files.filter(f => {
        const p = f.path.toLowerCase();
        return keywords.some(k => p.includes(k)) && !configFiles.includes(f);
      })
    : [];

  const selected = [...configFiles.slice(0, 2), ...matchedFiles.slice(0, 4)];

  const fetched = [];
  for (const file of selected) {
    const content = await fetchFileContent(workspace, repo, file.path, branch);
    if (content) fetched.push({ path: file.path, language: getLanguage(file.path), content });
  }

  return { structure, files: fetched };
};

export const getBitbucketRepos = async (workspace) => {
  try {
    const res = await fetch(`/api/bitbucket/repositories/${workspace}?pagelen=25`);
    if (res.ok) {
      const data = await res.json();
      return data.values || [];
    }
    return [];
  } catch {
    return [];
  }
};
