const DOMAIN = typeof __ATLASSIAN_DOMAIN__ !== 'undefined' ? __ATLASSIAN_DOMAIN__ : '';

export const getConfluenceBaseUrl = () => `https://${DOMAIN}/wiki`;

export const createConfluencePage = async (spaceKey, title, stories, solutioningHtml = null) => {
  if (!spaceKey) return { success: false, error: 'No Confluence space key configured. Please set it in Settings.' };

  const totalPoints = stories.reduce((s, st) => s + (st.adjustedPoints || 0), 0);

  // Fallback sprint overview (used only when solutioningHtml is not available)
  const fallbackStoriesHtml = stories.map(s => `
    <h3>${s.title} (${s.adjustedPoints} pts · ${s.priority || 'Medium'})</h3>
    <p>${s.description}</p>
    ${s.technicalNotes ? `<p><strong>Technical Notes:</strong> ${s.technicalNotes}</p>` : ''}
    <h4>Positive Acceptance Criteria</h4>
    <ul>${(s.acceptanceCriteria || []).map(ac => `<li>${ac}</li>`).join('')}</ul>
    ${(s.negativeAcceptanceCriteria || []).length > 0 ? `
      <h4>Negative Acceptance Criteria</h4>
      <ul>${s.negativeAcceptanceCriteria.map(ac => `<li>${ac}</li>`).join('')}</ul>
    ` : ''}
    ${(s.riskFlags || []).length > 0 ? `<h4>Risk Flags</h4><ul>${s.riskFlags.map(r => `<li>⚠️ ${r.text}</li>`).join('')}</ul>` : ''}
    <h4>Recommended Technical Approach</h4>
    <p>${s.solution?.options?.find(o => o.recommended)?.description || s.solution?.options?.[0]?.description || 'See story details.'}</p>
    <h4>QA Scenarios</h4>
    <pre><code class="language-gherkin">${(s.qaScenarios || []).join('\n\n')}</code></pre>
    <hr/>
  `).join('');

  const pageContent = solutioningHtml
    ? `
      <p><strong>Generated by SDLC Autopilot</strong> · ${new Date().toLocaleString()} · ${stories.length} stories · ${totalPoints} story points</p>
      <hr/>
      ${solutioningHtml}
    `
    : `
      <h1>SDLC Autopilot – Sprint Planning</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      <p><strong>Stories:</strong> ${stories.length} &nbsp;|&nbsp; <strong>Total Story Points:</strong> ${totalPoints}</p>
      <hr/>
      <h2>Stories &amp; Technical Proposals</h2>
      ${fallbackStoriesHtml}
    `;

  const body = {
    type: 'page',
    title: `SDLC Autopilot - ${title} - ${new Date().toLocaleDateString()}`,
    space: { key: spaceKey },
    body: {
      storage: {
        value: pageContent,
        representation: 'storage'
      }
    }
  };

  try {
    const res = await fetch('/api/confluence/content', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check' },
      body: JSON.stringify(body)
    });
    const data = await res.json();
    if (res.ok) {
      return {
        success: true,
        id: data.id,
        url: `${getConfluenceBaseUrl()}${data._links?.webui || `/spaces/${spaceKey}`}`
      };
    } else {
      return { success: false, error: data.message || JSON.stringify(data) };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const getConfluenceSpaces = async () => {
  try {
    const res = await fetch('/api/confluence/space?limit=20');
    if (res.ok) {
      const data = await res.json();
      return { spaces: data.results || [], error: null };
    }
    let errMsg = `HTTP ${res.status}`;
    try { const d = await res.json(); errMsg = d.message || d.error || errMsg; } catch {}
    return { spaces: [], error: errMsg };
  } catch (err) {
    return { spaces: [], error: err.message };
  }
};
