const DOMAIN = typeof __ATLASSIAN_DOMAIN__ !== 'undefined' ? __ATLASSIAN_DOMAIN__ : '';

export const getConfluenceBaseUrl = () => `https://${DOMAIN}/wiki`;

export const createConfluencePage = async (spaceKey, title, stories, solutioningHtml = null) => {
  if (!spaceKey) return { success: false, error: 'No Confluence space key configured. Please set it in Settings.' };

  const totalPoints = stories.reduce((s, st) => s + (st.adjustedPoints || 0), 0);

  // Fallback sprint overview (used only when solutioningHtml is not available)
  const fallbackStoriesHtml = stories.map(s => `
    <h3>${s.title} (${s.adjustedPoints} pts · ${s.priority || 'Medium'})</h3>
    <p>${s.description}</p>
    ${s.technicalNotes ? `<p><strong>Technical Notes:</strong> ${s.technicalNotes}</p>` : ''}
    <h4>Positive Acceptance Criteria</h4>
    <ul>${(s.acceptanceCriteria || []).map(ac => `<li>${ac}</li>`).join('')}</ul>
    ${(s.negativeAcceptanceCriteria || []).length > 0 ? `
      <h4>Negative Acceptance Criteria</h4>
      <ul>${s.negativeAcceptanceCriteria.map(ac => `<li>${ac}</li>`).join('')}</ul>
    ` : ''}
    ${(s.riskFlags || []).length > 0 ? `<h4>Risk Flags</h4><ul>${s.riskFlags.map(r => `<li>⚠️ ${r.text}</li>`).join('')}</ul>` : ''}
    <h4>Recommended Technical Approach</h4>
    <p>${s.solution?.options?.find(o => o.recommended)?.description || s.solution?.options?.[0]?.description || 'See story details.'}</p>
    <h4>QA Scenarios</h4>
    <pre><code class="language-gherkin">${(s.qaScenarios || []).join('\n\n')}</code></pre>
    <hr/>
  `).join('');

  const pageContent = solutioningHtml
    ? `
      <p><strong>Generated by SDLC Autopilot</strong> · ${new Date().toLocaleString()} · ${stories.length} stories · ${totalPoints} story points</p>
      <hr/>
      ${solutioningHtml}
    `
    : `
      <h1>SDLC Autopilot – Sprint Planning</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      <p><strong>Stories:</strong> ${stories.length} &nbsp;|&nbsp; <strong>Total Story Points:</strong> ${totalPoints}</p>
      <hr/>
      <h2>Stories &amp; Technical Proposals</h2>
      ${fallbackStoriesHtml}
    `;

  // Build a title that is unique even on same-day re-runs.
  // Format: "SDLC Autopilot - <title> - Mar 29, 2026, 3:45 PM"
  const baseTitle = `SDLC Autopilot - ${title} - ${new Date().toLocaleString()}`;

  const attemptCreate = async (pageTitle) => {
    const body = {
      type: 'page',
      title: pageTitle,
      space: { key: spaceKey },
      body: {
        storage: {
          value: pageContent,
          representation: 'storage'
        }
      }
    };
    const res = await fetch('/api/confluence/content', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check' },
      body: JSON.stringify(body)
    });
    const data = await res.json();
    return { ok: res.ok, data };
  };

  try {
    // Attempt 1: base title (should be unique thanks to time component)
    const { ok, data } = await attemptCreate(baseTitle);
    if (ok) {
      return {
        success: true,
        id: data.id,
        url: `${getConfluenceBaseUrl()}${data._links?.webui || `/spaces/${spaceKey}`}`
      };
    }

    // Only retry on explicit title-collision signatures — don't treat all 400s as collision
    const msg = (data.message || data.title || '').toLowerCase();
    const isTitleCollision = msg.includes('title') && (msg.includes('already exists') || msg.includes('exists'));

    if (isTitleCollision) {
      let lastError = data.message || JSON.stringify(data);
      for (let suffix = 2; suffix <= 5; suffix++) {
        const { ok: ok2, data: data2 } = await attemptCreate(`${baseTitle} (${suffix})`);
        if (ok2) {
          return {
            success: true,
            id: data2.id,
            url: `${getConfluenceBaseUrl()}${data2._links?.webui || `/spaces/${spaceKey}`}`
          };
        }
        lastError = data2.message || JSON.stringify(data2);
      }
      console.error('Confluence page creation failed after all suffix attempts:', lastError);
      return { success: false, error: lastError };
    }

    return { success: false, error: data.message || JSON.stringify(data) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const getConfluenceSpaces = async () => {
  try {
    const res = await fetch('/api/confluence/space?limit=20');
    if (res.ok) {
      const data = await res.json();
      return { spaces: data.results || [], error: null };
    }
    let errMsg = `HTTP ${res.status}`;
    try { const d = await res.json(); const detail = d.message || d.error; if (detail) errMsg = `HTTP ${res.status} — ${detail}`; } catch {}
    return { spaces: [], error: errMsg };
  } catch (err) {
    return { spaces: [], error: err.message };
  }
};
