// GitHub adapter — same shape as bitbucketService so gitService can dispatch to it.
// All calls go through the vite `/api/github` proxy, which injects the token.
const API = '/api/github';

const EXT_LANG_MAP = {
  js: 'javascript', jsx: 'jsx', ts: 'typescript', tsx: 'tsx',
  py: 'python', java: 'java', rb: 'ruby', go: 'go', rs: 'rust',
  cs: 'csharp', php: 'php', swift: 'swift', kt: 'kotlin',
  json: 'json', yaml: 'yaml', yml: 'yaml', md: 'markdown',
  html: 'html', css: 'css', scss: 'scss', sql: 'sql', sh: 'bash'
};
const getLanguage = (p) => {
  const ext = p.split('.').pop()?.toLowerCase();
  return EXT_LANG_MAP[ext] || ext || 'text';
};

// UTF-8 safe base64 (GitHub Contents API expects base64-encoded content)
const toBase64 = (str) => btoa(unescape(encodeURIComponent(str)));
const fromBase64 = (b64) => decodeURIComponent(escape(atob((b64 || '').replace(/\n/g, ''))));

const ghError = async (res) => {
  try { const d = await res.json(); return d.message || JSON.stringify(d); }
  catch { return `HTTP ${res.status}`; }
};

export const createGithubBranch = async (owner, repo, branchName, fromBranch = 'main') => {
  if (!owner || !repo) return { success: false, error: 'GitHub owner and repository not configured. Set them in Settings.' };
  try {
    // Resolve the source branch head SHA
    const refRes = await fetch(`${API}/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(fromBranch)}`);
    if (!refRes.ok) return { success: false, error: `Could not resolve base branch "${fromBranch}": ${await ghError(refRes)}` };
    const refData = await refRes.json();
    const sha = refData.object?.sha;
    if (!sha) return { success: false, error: `Base branch "${fromBranch}" has no commit SHA.` };

    const res = await fetch(`${API}/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha })
    });
    if (res.ok) {
      return { success: true, name: branchName, url: `https://github.com/${owner}/${repo}/tree/${branchName}` };
    }
    return { success: false, error: await ghError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const commitFilesToGithub = async (owner, repo, branchName, files, commitMessage = 'AI: Scaffolding generated by SDLC Autopilot') => {
  if (!owner || !repo || !files?.length) return { success: false, error: 'Missing parameters or code files.' };
  try {
    // Contents API — one PUT per file (create or update)
    for (const file of files) {
      const path = file.path.replace(/^\/+/, '');
      // Look up existing file SHA (needed to update rather than fail)
      let sha;
      const existing = await fetch(`${API}/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(branchName)}`);
      if (existing.ok) { const d = await existing.json(); sha = d.sha; }

      const res = await fetch(`${API}/repos/${owner}/${repo}/contents/${path}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: commitMessage, content: toBase64(file.content), branch: branchName, ...(sha ? { sha } : {}) })
      });
      if (!res.ok) return { success: false, error: `${path}: ${await ghError(res)}` };
    }
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const createGithubPR = async (owner, repo, branchName, storyTitle, checklist, issueKey, defaultBranch = 'main') => {
  if (!owner || !repo) return { success: false, error: 'GitHub owner and repository not configured.' };
  const body = [
    checklist ? `## PR Review Checklist\n\n${checklist}` : '',
    `---\n*Generated by SDLC Autopilot${issueKey ? ` · Jira: ${issueKey}` : ''}*`
  ].filter(Boolean).join('\n\n');
  try {
    const res = await fetch(`${API}/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: issueKey ? `[${issueKey}] ${storyTitle}` : storyTitle,
        head: branchName,
        base: defaultBranch,
        body
      })
    });
    const data = await res.json();
    if (res.ok) return { success: true, id: data.number, url: data.html_url };
    return { success: false, error: data.message || JSON.stringify(data) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const deleteGithubBranch = async (owner, repo, branch) => {
  if (!owner || !repo || !branch) return { success: false, error: 'GitHub owner, repository and branch are required.' };
  try {
    const res = await fetch(`${API}/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(branch)}`, {
      method: 'DELETE'
    });
    if (res.ok) return { success: true };
    return { success: false, error: await ghError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const closeGithubPR = async (owner, repo, number) => {
  if (!owner || !repo || !number) return { success: false, error: 'GitHub owner, repository and PR number are required.' };
  try {
    const res = await fetch(`${API}/repos/${owner}/${repo}/pulls/${encodeURIComponent(number)}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ state: 'closed' })
    });
    if (res.ok) return { success: true };
    return { success: false, error: await ghError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const getGithubRepos = async () => {
  try {
    const res = await fetch(`${API}/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member`);
    if (!res.ok) return { repos: [], error: await ghError(res) };
    const data = await res.json();
    return { repos: (data || []).map(r => ({ owner: r.owner?.login, name: r.name, fullName: r.full_name, defaultBranch: r.default_branch })), error: null };
  } catch (err) {
    return { repos: [], error: err.message };
  }
};

export const getGithubBranches = async (owner, repo) => {
  if (!owner || !repo) return [];
  try {
    const res = await fetch(`${API}/repos/${owner}/${repo}/branches?per_page=100`);
    if (!res.ok) return [];
    const data = await res.json();
    return (data || []).map(b => b.name);
  } catch {
    return [];
  }
};

export const fetchGithubRepoContext = async (owner, repo, branch = 'main', storyLabels = [], storyTitle = '') => {
  if (!owner || !repo) return { structure: '', files: [] };
  try {
    const treeRes = await fetch(`${API}/repos/${owner}/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`);
    if (!treeRes.ok) return { structure: '', files: [] };
    const treeData = await treeRes.json();
    const blobs = (treeData.tree || []).filter(t => t.type === 'blob');
    const paths = blobs.map(b => b.path);
    const dirs = [...new Set((treeData.tree || []).filter(t => t.type === 'tree').map(t => t.path))];

    const structure = [
      `Directories: ${dirs.join(', ').slice(0, 400) || 'none'}`,
      `Files (${paths.length}): ${paths.join(', ').slice(0, 600)}`
    ].join('\n');

    const configNames = ['package.json', 'requirements.txt', 'go.mod', 'pom.xml', 'index.js', 'app.js', 'main.py', 'app.py', 'main.ts', 'index.ts', 'server.js'];
    const configPaths = paths.filter(p => configNames.some(n => p.endsWith(n)));
    const keywords = [...storyLabels, ...storyTitle.toLowerCase().split(/\s+/).filter(w => w.length > 3)].map(k => k.toLowerCase());
    const matched = keywords.length ? paths.filter(p => keywords.some(k => p.toLowerCase().includes(k)) && !configPaths.includes(p)) : [];
    const selected = [...configPaths.slice(0, 2), ...matched.slice(0, 4)];

    const files = [];
    for (const path of selected) {
      const res = await fetch(`${API}/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`);
      if (!res.ok) continue;
      const d = await res.json();
      const content = d.content ? fromBase64(d.content) : '';
      if (content) files.push({ path, language: getLanguage(path), content: content.slice(0, 3000) });
    }
    return { structure, files };
  } catch {
    return { structure: '', files: [] };
  }
};
