// GitLab adapter — same shape as bitbucketService so gitService can dispatch to it.
// All calls go through the vite `/api/gitlab` proxy, which injects the token.
// `project` is a GitLab project ID (number) or URL-encoded "group/project" path.
const API = '/api/gitlab';

const EXT_LANG_MAP = {
  js: 'javascript', jsx: 'jsx', ts: 'typescript', tsx: 'tsx',
  py: 'python', java: 'java', rb: 'ruby', go: 'go', rs: 'rust',
  cs: 'csharp', php: 'php', swift: 'swift', kt: 'kotlin',
  json: 'json', yaml: 'yaml', yml: 'yaml', md: 'markdown',
  html: 'html', css: 'css', scss: 'scss', sql: 'sql', sh: 'bash'
};
const getLanguage = (p) => {
  const ext = p.split('.').pop()?.toLowerCase();
  return EXT_LANG_MAP[ext] || ext || 'text';
};

const pid = (project) => encodeURIComponent(project);
const glError = async (res) => {
  try { const d = await res.json(); return d.message ? (typeof d.message === 'string' ? d.message : JSON.stringify(d.message)) : (d.error || `HTTP ${res.status}`); }
  catch { return `HTTP ${res.status}`; }
};

export const createGitlabBranch = async (project, branchName, fromBranch = 'main') => {
  if (!project) return { success: false, error: 'GitLab project not configured. Set it in Settings.' };
  try {
    const res = await fetch(`${API}/projects/${pid(project)}/repository/branches?branch=${encodeURIComponent(branchName)}&ref=${encodeURIComponent(fromBranch)}`, {
      method: 'POST'
    });
    const data = await res.json();
    if (res.ok) return { success: true, name: data.name, url: data.web_url || '' };
    return { success: false, error: data.message || JSON.stringify(data) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const commitFilesToGitlab = async (project, branchName, files, commitMessage = 'AI: Scaffolding generated by SDLC Autopilot') => {
  if (!project || !files?.length) return { success: false, error: 'Missing parameters or code files.' };
  try {
    // Decide create vs update per file based on existence on the target branch
    const actions = [];
    for (const file of files) {
      const filePath = file.path.replace(/^\/+/, '');
      const exists = await fetch(`${API}/projects/${pid(project)}/repository/files/${encodeURIComponent(filePath)}?ref=${encodeURIComponent(branchName)}`);
      actions.push({ action: exists.ok ? 'update' : 'create', file_path: filePath, content: file.content });
    }
    const res = await fetch(`${API}/projects/${pid(project)}/repository/commits`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ branch: branchName, commit_message: commitMessage, actions })
    });
    if (res.ok) return { success: true };
    return { success: false, error: await glError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const createGitlabMR = async (project, branchName, storyTitle, checklist, issueKey, targetBranch = 'main') => {
  if (!project) return { success: false, error: 'GitLab project not configured.' };
  const description = [
    checklist ? `## PR Review Checklist\n\n${checklist}` : '',
    `---\n*Generated by SDLC Autopilot${issueKey ? ` · Jira: ${issueKey}` : ''}*`
  ].filter(Boolean).join('\n\n');
  try {
    const res = await fetch(`${API}/projects/${pid(project)}/merge_requests`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        source_branch: branchName,
        target_branch: targetBranch,
        title: issueKey ? `[${issueKey}] ${storyTitle}` : storyTitle,
        description
      })
    });
    const data = await res.json();
    if (res.ok) return { success: true, id: data.iid, url: data.web_url };
    return { success: false, error: data.message || JSON.stringify(data) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const deleteGitlabBranch = async (project, branch) => {
  if (!project || !branch) return { success: false, error: 'GitLab project and branch are required.' };
  try {
    const res = await fetch(`${API}/projects/${pid(project)}/repository/branches/${encodeURIComponent(branch)}`, {
      method: 'DELETE'
    });
    if (res.ok) return { success: true };
    return { success: false, error: await glError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const closeGitlabMR = async (project, iid) => {
  if (!project || !iid) return { success: false, error: 'GitLab project and merge request iid are required.' };
  try {
    const res = await fetch(`${API}/projects/${pid(project)}/merge_requests/${encodeURIComponent(iid)}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ state_event: 'close' })
    });
    if (res.ok) return { success: true };
    return { success: false, error: await glError(res) };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

export const getGitlabProjects = async () => {
  try {
    const res = await fetch(`${API}/projects?membership=true&per_page=100&order_by=last_activity_at&simple=true`);
    if (!res.ok) return { projects: [], error: await glError(res) };
    const data = await res.json();
    return { projects: (data || []).map(p => ({ id: p.id, name: p.name_with_namespace || p.path_with_namespace, path: p.path_with_namespace, defaultBranch: p.default_branch })), error: null };
  } catch (err) {
    return { projects: [], error: err.message };
  }
};

export const getGitlabBranches = async (project) => {
  if (!project) return [];
  try {
    const res = await fetch(`${API}/projects/${pid(project)}/repository/branches?per_page=100`);
    if (!res.ok) return [];
    const data = await res.json();
    return (data || []).map(b => b.name);
  } catch {
    return [];
  }
};

export const fetchGitlabRepoContext = async (project, branch = 'main', storyLabels = [], storyTitle = '') => {
  if (!project) return { structure: '', files: [] };
  try {
    const treeRes = await fetch(`${API}/projects/${pid(project)}/repository/tree?recursive=true&per_page=100&ref=${encodeURIComponent(branch)}`);
    if (!treeRes.ok) return { structure: '', files: [] };
    const tree = await treeRes.json();
    const filePaths = (tree || []).filter(t => t.type === 'blob').map(t => t.path);
    const dirs = [...new Set((tree || []).filter(t => t.type === 'tree').map(t => t.path))];

    const structure = [
      `Directories: ${dirs.join(', ').slice(0, 400) || 'none'}`,
      `Files (${filePaths.length}): ${filePaths.join(', ').slice(0, 600)}`
    ].join('\n');

    const configNames = ['package.json', 'requirements.txt', 'go.mod', 'pom.xml', 'index.js', 'app.js', 'main.py', 'app.py', 'main.ts', 'index.ts', 'server.js'];
    const configPaths = filePaths.filter(p => configNames.some(n => p.endsWith(n)));
    const keywords = [...storyLabels, ...storyTitle.toLowerCase().split(/\s+/).filter(w => w.length > 3)].map(k => k.toLowerCase());
    const matched = keywords.length ? filePaths.filter(p => keywords.some(k => p.toLowerCase().includes(k)) && !configPaths.includes(p)) : [];
    const selected = [...configPaths.slice(0, 2), ...matched.slice(0, 4)];

    const files = [];
    for (const path of selected) {
      const res = await fetch(`${API}/projects/${pid(project)}/repository/files/${encodeURIComponent(path)}/raw?ref=${encodeURIComponent(branch)}`);
      if (!res.ok) continue;
      const content = await res.text();
      if (content) files.push({ path, language: getLanguage(path), content: content.slice(0, 3000) });
    }
    return { structure, files };
  } catch {
    return { structure: '', files: [] };
  }
};
